// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzgqtiyjhsdcblfwdoxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6Z3F0aXlqaHNkY2JsZndkb3hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2Njg2NDYsImV4cCI6MjA2MzI0NDY0Nn0.8IuZguu2NAuuwsG9a8eKVFH-FKQ4JrVb0eSQ7H9xo8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);